//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denetim_Takip_Sistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class belge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public belge()
        {
            this.bitis_tarihi = new HashSet<bitis_tarihi>();
            this.denetim = new HashSet<denetim>();
            this.dosya_bilgisi = new HashSet<dosya_bilgisi>();
            this.nott = new HashSet<nott>();
        }
    
        public int belge_id { get; set; }
        public Nullable<int> belge_belge_tipi_id { get; set; }
        public string belge_adi { get; set; }
        public string belge_durum { get; set; }
        public string belge_eklyn_kllnc { get; set; }
        public string belge_gncllyn_kllnc { get; set; }
        public Nullable<System.DateTime> belge_eklnm_trh { get; set; }
        public Nullable<System.DateTime> belge_gncllnm_trh { get; set; }
        public string belge_acklm { get; set; }
    
        public virtual belge_tipi belge_tipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitis_tarihi> bitis_tarihi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<denetim> denetim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dosya_bilgisi> dosya_bilgisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nott> nott { get; set; }
    }
}
