//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denetim_Takip_Sistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitis_tarihi
    {
        public int bitis_trh_id { get; set; }
        public Nullable<int> bitis_trh_belge_id { get; set; }
        public Nullable<System.DateTime> bitis_trh_bitis_trh { get; set; }
        public string bitis_trh_durum { get; set; }
        public string bitis_trh_acklm { get; set; }
        public string bitis_trh_eklyn_kllnc { get; set; }
        public string bitis_trh_gncllyn_kllnc { get; set; }
        public Nullable<System.DateTime> bitis_trh_eklnm_trh { get; set; }
        public Nullable<System.DateTime> bitis_trh_gncllnm_trh { get; set; }
    
        public virtual belge belge { get; set; }
    }
}
