//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denetim_Takip_Sistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class denetim
    {
        public int dntm_id { get; set; }
        public Nullable<int> dntm_belge_id { get; set; }
        public string dntm_adi { get; set; }
        public Nullable<System.DateTime> dntm_bslngc_trh { get; set; }
        public Nullable<System.DateTime> dntm_bitis_trh { get; set; }
        public string dntm_giren_kisi { get; set; }
        public string dntm_giren_prsnl { get; set; }
        public Nullable<int> dntm_bldrm_srs { get; set; }
        public string dntm_durum { get; set; }
        public string dntm_acklm { get; set; }
        public string dntm_eklyn_kllnc { get; set; }
        public string dntm_gncllyn_kllnc { get; set; }
        public Nullable<System.DateTime> dntm_eklnm_trh { get; set; }
        public Nullable<System.DateTime> dntm_gncllnm_trh { get; set; }
    
        public virtual belge belge { get; set; }
    }
}
