//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denetim_Takip_Sistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class dosya_bilgisi
    {
        public int dosya_blgs_id { get; set; }
        public Nullable<int> dosya_blgs_belge_id { get; set; }
        public string dosya_blgs_dosya { get; set; }
        public string dosya_blgs_durum { get; set; }
        public string dosya_blgs_aciklama { get; set; }
        public string dosya_blgs_eklyn_kllnc { get; set; }
        public string dosya_blgs_gncllyn_kllnc { get; set; }
        public Nullable<System.DateTime> dosya_blgs_eklnm_trh { get; set; }
        public Nullable<System.DateTime> dosya_blgs_gncllnm_trh { get; set; }
    
        public virtual belge belge { get; set; }
    }
}
