//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denetim_Takip_Sistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kllnc_id { get; set; }
        public string kllnc_kllncad { get; set; }
        public string kllnc_adi { get; set; }
        public string kllnc_kmlk_no { get; set; }
        public Nullable<System.DateTime> kllnc_dgm_trh { get; set; }
        public string kllnc_epsta { get; set; }
        public string kllnc_cep_tel { get; set; }
        public string kllnc_rol { get; set; }
        public string kllnc_prl { get; set; }
        public byte[] kllnc_resim { get; set; }
        public string kllnc_eklyn_kllnc { get; set; }
        public string kllnc_gnclln_kllnc { get; set; }
        public Nullable<System.DateTime> kllnc_eklnm_trh { get; set; }
        public Nullable<System.DateTime> kllnc_gncllnm_trh { get; set; }
        public string kllnc_pll_rst { get; set; }
    }
}
