//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denetim_Takip_Sistemi.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class nott
    {
        public int not_id { get; set; }
        public Nullable<int> not_belge_id { get; set; }
        public string not_konu { get; set; }
        public string not_durum { get; set; }
        public string not_acklm { get; set; }
        public string not_eklyn_kllnc { get; set; }
        public string not_gncllyn_kllnc { get; set; }
        public Nullable<System.DateTime> not_eklnm_trh { get; set; }
        public Nullable<System.DateTime> not_gncllnm_trh { get; set; }
    
        public virtual belge belge { get; set; }
    }
}
